### ISSUE TITLE
[Bug/Glitch] NCIC Editor

### ISSUE THREAD

**Issue by GamerXsakuboy99** [Matt4499/opencad#53]
### NCIC editor panel
Most of stuff is either in wrong places and  aren't not editable at all via Website, So changes need to be done via DB itself.
And issuing agency is not shown on NCIC citations & arrests part.

_pictures_
![NCIC-arrests](https://user-images.githubusercontent.com/25152858/101286929-0c227780-37f6-11eb-9155-ddc74532f732.png)
![NCIC-names](https://user-images.githubusercontent.com/25152858/101286930-0d53a480-37f6-11eb-8895-af0d32d61e59.png)
**OpenCAD Version: 0.3.2**
> Had wrong version number..

**Method of Hosting (XAMPP/cPanel/ETC): cPanel **

**Comment by Matt4499** [comment]
I believe this could just be due to the vanilla OpenCAD installer being completely broken and doesn't even import the SQL files, nor in order, regardless I will still look at it

**Comment by GamerXsakuboy99** [comment]
I replaced broken 0.3.1 with your version fully without using installer at all, and looking to the fill itself.  it's a mixed writing.
on file: ncicAdminActions.php lines 120 & 122, and when compared to lines 100 & 102.

I did fix this on my site today by switching over lines 120 & 122.

**Comment by Matt4499** [comment]
by `with your version` are you referring to the master branch or dev branch ?

**Comment by GamerXsakuboy99** [comment]
master branch,  (i did try dev branch on my local webserver... i did not work)

**Comment by Matt4499** [comment]
as expected, I believe I have only made a single change to the master branch so far. and the dev branch has incomplete code in it, so it probably won't work. I'm going to finish up a working version within the next couple of days, thank you for the report and additional information.

**Comment by Matt4499** [comment]
fixed with https://github.com/Matt4499/opencad/commit/bc15a1d2aa568c6abe508743d3a8d63a1aabc38f

**Comment by Matt4499** [comment]
Update:

`issued_by_agency` is not even a valid column in the DB (is this even implemented yet?)
fixed the things being in the wrong place
i don't think some of these were intended to be editable, more like logs. (theres no edit code for them, only name, plate, id, and plateid)

https://github.com/Matt4499/opencad/issues/11
