### ISSUE TITLE
[Bug/Glitch] Slow response time on Civilian & Dispatch page

### ISSUE THREAD

**Issue by GamerXsakuboy99** [Matt4499/opencad#54]
Dispatch and civilian pages are very slow to respond the first 30 ~ 60sec, after that they work normally and smoothly.
My Webhost has everything in updated to newest versions few weeks ago.

_no clue if this ha been fixed already / only i have issues with it. but better safe and sorry than not to report this :D_

**OpenCAD Version: 0.3.2**

**Method of Hosting (XAMPP/cPanel/ETC): cPanel **

**Comment by Matt4499** [comment]
Can you go into your developer tools and view the network tab waterfall, and send a picture? Also, do you have any other sites/programs running on your database, such as forums, etc. ?
![image](https://user-images.githubusercontent.com/33269887/101296056-f22d6880-37e6-11eb-8987-6bff5ee3c57d.png)

**Comment by GamerXsakuboy99** [comment]
after doing some testing, i determine that fault was on my side.  

I did run multiple tests on my different computers and on those response time was good.

so fault was on my main computer web browser.

**Comment by Matt4499** [comment]
Glad to hear it, and thanks for the report, regardless of the outcome.
