### ISSUE TITLE
[Bug/Glitch] Warrant editor only shows non-violent/violent DB numbers

### ISSUE THREAD

**Issue by GamerXsakuboy99** [Matt4499/opencad#55]
Warrant editor in website shows db's "warrant_violent" line and does not show the warrant description at all.

But i can tell that Warrant creator in Dispatch page does work, with description shown and categorizing them between Violent and non-violent

![Screenshot 2020-12-07 045538](https://user-images.githubusercontent.com/25152858/101304259-909de600-3848-11eb-97b6-e4e62eb44e1b.png)
![Screenshot 2020-12-07 46045615](https://user-images.githubusercontent.com/25152858/101304261-91367c80-3848-11eb-97ee-d8f7bc7cee46.png)

**OpenCAD Version: Master branch (0.3.2)**

**Method of Hosting (XAMPP/cPanel/ETC): cPanel**

**Comment by Matt4499** [comment]
fixed with https://github.com/Matt4499/opencad/commit/bc15a1d2aa568c6abe508743d3a8d63a1aabc38f
also fixed a weird formatting error
