### ISSUE TITLE
[Bug/Glitch] oc_GTAV_DATA.sql missing <DB_PREFIX>

### ISSUE THREAD

**Issue by GamerXsakuboy99** [Matt4499/opencad#57]
as title says.  file is missing <DB_PREFIX> on `INSERT INTO colors (id, color_group, color_name) VALUES` code.
So it's a extra step for users to add the prefix to this file.

But ofc if you are going to remove prefix system then this issue can be closed :D

**OpenCAD Version: Master branch**

**Method of Hosting (XAMPP/cPanel/ETC): cPanel**

**Comment by Matt4499** [comment]
prefix system has been removed in 0.3.3
it's completely useless and pointless to have been added.
table prefix by default is now `OC_`
